openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
paths:
  /messages:
    post:
      summary: Create a new message
      tags:
        - Message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Message"
      responses:
        "200":
          description: Message was created
          content:
            application/json:
              schema:
                type: string
        "404":
          description: Sender or receiver does not exist
        "400":
          description: Sender and receiver cannot be the same
  /messages/{receiver}:
    get:
      summary: Get all messages sent to a user
      tags:
        - Message
      parameters:
        - name: receiver
          in: path
          required: true
          description: The receiver of the messages
          schema:
            type: string
      responses:
        "200":
          description: A list of messages received by the user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Message"
        "404":
          description: Received does not exist

  /messages/{messageId}:
    post:
      summary: Update a message, accepted or rejected
      tags:
        - Message
      parameters:
        - name: messageId
          in: path
          required: true
          description: The id of the message
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - accepted
              properties:
                accepted:
                  type: boolean

      responses:
        "200":
          description: Message was updated
          content:
            application/json:
              schema:
                type: string
        "404":
          description: Message does not exist

components:
  schemas:
    Message:
      type: object
      required:
        - _id
        - sender
        - receiver
      properties:
        _id:
          type: string
          description: The id of the message
        sender:
          type: string
          description: sender of the message
        receiver:
          type: string
          description: receiver of the message
      example:
        sender: user1
        receiver: user2

tags:
  - name: Message
    description: The Message managing API
