openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
paths:
  /passwords:
    post:
      summary: Create a new password
      tags:
        - Password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - "url"
                - "password"
                - "owner"
              properties:
                url:
                  type: string
                  description: The URL of the password
                password:
                  type: string
                  description: The password
                owner:
                  type: string
                  description: The owner of the password
      responses:
        "200":
          description: Password was created
          content:
            application/json:
              schema:
                type: string
        "404":
          description: Owner does not exist
        "400":
          description: Owner and shared_with cannot be the same

  /passwords/{username}:
    get:
      summary: Get all passwords owned or shared with a user
      tags:
        - Password
      parameters:
        - name: username
          in: path
          required: true
          description: The user to get the passwords
          schema:
            type: string
      responses:
        "200":
          description: A list of passwords owned or shared with the user
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    url:
                      type: string
                    password:
                      type: string
                    owner:
                      type: string
        "404":
          description: User does not exist

  /passwords/{passwordId}:
    put:
      summary: Update a password
      tags:
        - Password
      parameters:
        - name: passwordId
          in: path
          required: true
          description: The id of the password
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - password
                - url
              properties:
                password:
                  type: string
                  description: The password
                url:
                  type: string
                  description: The URL of the password
      responses:
        "200":
          description: Password was updated
        "404":
          description: Password does not exist
    delete:
      summary: Delete a password
      tags:
        - Password
      parameters:
        - name: passwordId
          in: path
          required: true
          description: The id of the password
          schema:
            type: string
      responses:
        "200":
          description: Password was deleted
        "404":
          description: Password does not exist

components:
  schemas:
    Password:
      type: object
      required:
        - url
        - password
        - owner
        - shared_with
      properties:
        url:
          type: string
          description: The URL of the password
        password:
          type: string
          description: The password
        owner:
          type: string
          description: The owner of the password
        shared_with:
          type: array
          items:
            type: string
          description: The users the password is shared with
      example:
        url: https://www.example.com
        password: password123
        owner: user1
        shared_with:
          - user2
          - user3

tags:
  - name: Password
    description: The Password managing API
